/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginInfo"];
                    "text/json": components["schemas"]["LoginInfo"];
                    "application/*+json": components["schemas"]["LoginInfo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eventlogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateEventLogDto"];
                    "text/json": components["schemas"]["CreateEventLogDto"];
                    "application/*+json": components["schemas"]["CreateEventLogDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EventLogGenericResponse"];
                        "application/json": components["schemas"]["EventLogGenericResponse"];
                        "text/json": components["schemas"]["EventLogGenericResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eventlogs/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateEventLogsDto"];
                    "text/json": components["schemas"]["CreateEventLogsDto"];
                    "application/*+json": components["schemas"]["CreateEventLogsDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EventLogIEnumerableGenericResponse"];
                        "application/json": components["schemas"]["EventLogIEnumerableGenericResponse"];
                        "text/json": components["schemas"]["EventLogIEnumerableGenericResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eventlogs/user/{userId}/last": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DateTimeOffsetNullableGenericResponse"];
                        "application/json": components["schemas"]["DateTimeOffsetNullableGenericResponse"];
                        "text/json": components["schemas"]["DateTimeOffsetNullableGenericResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MetaResponseGenericResponse"];
                        "application/json": components["schemas"]["MetaResponseGenericResponse"];
                        "text/json": components["schemas"]["MetaResponseGenericResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StringGenericResponse"];
                        "application/json": components["schemas"]["StringGenericResponse"];
                        "text/json": components["schemas"]["StringGenericResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateUserDto"];
                    "text/json": components["schemas"]["CreateUserDto"];
                    "application/*+json": components["schemas"]["CreateUserDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserGenericResponse"];
                        "application/json": components["schemas"]["UserGenericResponse"];
                        "text/json": components["schemas"]["UserGenericResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateUserDto"];
                    "text/json": components["schemas"]["UpdateUserDto"];
                    "application/*+json": components["schemas"]["UpdateUserDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserGenericResponse"];
                        "application/json": components["schemas"]["UserGenericResponse"];
                        "text/json": components["schemas"]["UserGenericResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/users/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserGenericResponse"];
                        "application/json": components["schemas"]["UserGenericResponse"];
                        "text/json": components["schemas"]["UserGenericResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    email?: string;
                    accepted?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddUserToEntityRequest: {
            roles: components["schemas"]["Roles"][] | null;
        };
        CreateAthletesDto: {
            athletes?: components["schemas"]["CreateUserDto"][] | null;
        };
        CreateCoachesDto: {
            coaches?: components["schemas"]["CreateUserDto"][] | null;
        };
        CreateEntityRequest: {
            name: string | null;
            description?: string | null;
            entityType?: string | null;
            /** Format: uuid */
            parentEntityId?: string | null;
        };
        CreateEventLogDto: {
            eventType: string | null;
            /** Format: date-time */
            timestamp: string;
            /** Format: uuid */
            userId: string;
            eventData?: string | null;
            source?: string | null;
            /** Format: uuid */
            entityId?: string | null;
            sessionId?: string | null;
        };
        CreateEventLogsDto: {
            eventLogs?: components["schemas"]["CreateEventLogDto"][] | null;
        };
        CreateUserDto: {
            firstName?: string | null;
            lastName?: string | null;
            email?: string | null;
        };
        DateTimeOffsetNullableGenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
            /** Format: date-time */
            data?: string | null;
        };
        Entity: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: uuid */
            lastModifiedBy?: string | null;
            /** Format: date-time */
            lastModifiedAt?: string | null;
            isDeleted?: boolean;
            /** Format: date-time */
            deletedAt?: string | null;
            /** Format: uuid */
            deletedBy?: string | null;
            name: string | null;
            description?: string | null;
            entityType?: string | null;
            /** Format: uuid */
            parentEntityId?: string | null;
        };
        EntityGenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
            data?: components["schemas"]["Entity"];
        };
        EntityIEnumerableGenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
            data?: components["schemas"]["Entity"][] | null;
        };
        EventLog: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: uuid */
            lastModifiedBy?: string | null;
            /** Format: date-time */
            lastModifiedAt?: string | null;
            eventType: string | null;
            /** Format: date-time */
            timestamp: string;
            /** Format: uuid */
            userId: string;
            eventData?: string | null;
            source?: string | null;
            /** Format: uuid */
            entityId?: string | null;
            ipAddress?: string | null;
            userAgent?: string | null;
            sessionId?: string | null;
        };
        EventLogGenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
            data?: components["schemas"]["EventLog"];
        };
        EventLogIEnumerableGenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
            data?: components["schemas"]["EventLog"][] | null;
        };
        GenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
        };
        LoginInfo: {
            username: string | null;
            password: string | null;
        };
        MetaResponse: {
            version?: string | null;
            /** Format: date-time */
            lastUpdated?: string;
            userId?: string | null;
            email?: string | null;
        };
        MetaResponseGenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
            data?: components["schemas"]["MetaResponse"];
        };
        /** @enum {string} */
        Roles: "Athlete" | "Coach" | "EntityAdmin" | "OrganizationAdmin" | "Admin" | "ServiceAccount" | "AlphaTester" | "BetaTester" | "SuperUser";
        StringGenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
            data?: string | null;
        };
        UpdateEntityRequest: {
            name: string | null;
            description?: string | null;
            entityType?: string | null;
            /** Format: uuid */
            parentEntityId?: string | null;
        };
        UpdateUserDto: {
            /** Format: uuid */
            id?: string;
            firstName?: string | null;
            lastName?: string | null;
            /** Format: int32 */
            heightInInches?: number | null;
            colorHex?: string | null;
            /** Format: date */
            birthdate?: string | null;
            /** Format: byte */
            thumbnailImage?: string | null;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: uuid */
            lastModifiedBy?: string | null;
            /** Format: date-time */
            lastModifiedAt?: string | null;
            isDeleted?: boolean;
            /** Format: date-time */
            deletedAt?: string | null;
            /** Format: uuid */
            deletedBy?: string | null;
            externalId?: string | null;
            firstName?: string | null;
            lastName?: string | null;
            /** Format: int32 */
            heightInInches?: number | null;
            colorHex?: string | null;
            email: string | null;
            /** Format: date */
            birthdate?: string | null;
            /** Format: byte */
            thumbnailImage?: string | null;
            acceptedTerms?: boolean;
            confirmedAge?: boolean;
            isEmailVerified?: boolean;
            roles?: components["schemas"]["Roles"][] | null;
        };
        UserGenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
            data?: components["schemas"]["User"];
        };
        UserIEnumerableGenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
            data?: components["schemas"]["User"][] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
