/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticates a user and returns an access token. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description The login credentials. */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginInfo"];
                    "text/json": components["schemas"]["LoginInfo"];
                    "application/*+json": components["schemas"]["LoginInfo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets all root-level entities (entities without a parent). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EntityIEnumerableGenericResponse"];
                        "application/json": components["schemas"]["EntityIEnumerableGenericResponse"];
                        "text/json": components["schemas"]["EntityIEnumerableGenericResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Creates a new entity. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description The entity creation request. */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateEntityRequest"];
                    "text/json": components["schemas"]["CreateEntityRequest"];
                    "application/*+json": components["schemas"]["CreateEntityRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EntityGenericResponse"];
                        "application/json": components["schemas"]["EntityGenericResponse"];
                        "text/json": components["schemas"]["EntityGenericResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets all entities in the system. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EntityIEnumerableGenericResponse"];
                        "application/json": components["schemas"]["EntityIEnumerableGenericResponse"];
                        "text/json": components["schemas"]["EntityIEnumerableGenericResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/id/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets a specific entity by its identifier. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The unique identifier of the entity. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EntityGenericResponse"];
                        "application/json": components["schemas"]["EntityGenericResponse"];
                        "text/json": components["schemas"]["EntityGenericResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/type/{entityType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets all entities of a specific type. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The type of entities to retrieve. */
                    entityType: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EntityIEnumerableGenericResponse"];
                        "application/json": components["schemas"]["EntityIEnumerableGenericResponse"];
                        "text/json": components["schemas"]["EntityIEnumerableGenericResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/parent/{parentEntityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets all child entities of a specific parent entity. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The unique identifier of the parent entity. */
                    parentEntityId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EntityIEnumerableGenericResponse"];
                        "application/json": components["schemas"]["EntityIEnumerableGenericResponse"];
                        "text/json": components["schemas"]["EntityIEnumerableGenericResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Updates an existing entity. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The unique identifier of the entity to update. */
                    id: string;
                };
                cookie?: never;
            };
            /** @description The entity update request. */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateEntityRequest"];
                    "text/json": components["schemas"]["UpdateEntityRequest"];
                    "application/*+json": components["schemas"]["UpdateEntityRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EntityGenericResponse"];
                        "application/json": components["schemas"]["EntityGenericResponse"];
                        "text/json": components["schemas"]["EntityGenericResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Deletes an entity. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The unique identifier of the entity to delete. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GenericResponse"];
                        "application/json": components["schemas"]["GenericResponse"];
                        "text/json": components["schemas"]["GenericResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/{entityId}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets all users for a specific entity. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The unique identifier of the entity. */
                    entityId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserIEnumerableGenericResponse"];
                        "application/json": components["schemas"]["UserIEnumerableGenericResponse"];
                        "text/json": components["schemas"]["UserIEnumerableGenericResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/{entityId}/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adds a user to an entity with specified roles. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The unique identifier of the entity. */
                    entityId: string;
                    /** @description The unique identifier of the user to add. */
                    userId: string;
                };
                cookie?: never;
            };
            /** @description The request containing roles to assign. */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AddUserToEntityRequest"];
                    "text/json": components["schemas"]["AddUserToEntityRequest"];
                    "application/*+json": components["schemas"]["AddUserToEntityRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GenericResponse"];
                        "application/json": components["schemas"]["GenericResponse"];
                        "text/json": components["schemas"]["GenericResponse"];
                    };
                };
            };
        };
        /** Removes a user from an entity. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The unique identifier of the entity. */
                    entityId: string;
                    /** @description The unique identifier of the user to remove. */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GenericResponse"];
                        "application/json": components["schemas"]["GenericResponse"];
                        "text/json": components["schemas"]["GenericResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eventlogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates a new event log entry. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description The event log creation request. */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateEventLogDto"];
                    "text/json": components["schemas"]["CreateEventLogDto"];
                    "application/*+json": components["schemas"]["CreateEventLogDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EventLogGenericResponse"];
                        "application/json": components["schemas"]["EventLogGenericResponse"];
                        "text/json": components["schemas"]["EventLogGenericResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eventlogs/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates multiple event log entries in a single batch operation. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description The batch event logs creation request. */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateEventLogsDto"];
                    "text/json": components["schemas"]["CreateEventLogsDto"];
                    "application/*+json": components["schemas"]["CreateEventLogsDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EventLogIEnumerableGenericResponse"];
                        "application/json": components["schemas"]["EventLogIEnumerableGenericResponse"];
                        "text/json": components["schemas"]["EventLogIEnumerableGenericResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eventlogs/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Searches event logs with flexible filtering and paging. Requires admin authorization. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description The search criteria including filters and paging parameters. */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EventLogSearchCriteriaDto"];
                    "text/json": components["schemas"]["EventLogSearchCriteriaDto"];
                    "application/*+json": components["schemas"]["EventLogSearchCriteriaDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EventLogIEnumerablePagedResponse"];
                        "application/json": components["schemas"]["EventLogIEnumerablePagedResponse"];
                        "text/json": components["schemas"]["EventLogIEnumerablePagedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eventlogs/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets all event log types */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StringIEnumerableGenericResponse"];
                        "application/json": components["schemas"]["StringIEnumerableGenericResponse"];
                        "text/json": components["schemas"]["StringIEnumerableGenericResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eventlogs/user/{userId}/last": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets the timestamp of the last event log for a specific user. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The unique identifier of the user. */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DateTimeOffsetNullableGenericResponse"];
                        "application/json": components["schemas"]["DateTimeOffsetNullableGenericResponse"];
                        "text/json": components["schemas"]["DateTimeOffsetNullableGenericResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eventlogs/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets event log summary data grouped by user with monthly aggregates.
         *     Includes the number of videos captured (RecordingStopped events) and number of days used per month.
         *     Requires admin authorization.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EventLogUserSummaryIEnumerableGenericResponse"];
                        "application/json": components["schemas"]["EventLogUserSummaryIEnumerableGenericResponse"];
                        "text/json": components["schemas"]["EventLogUserSummaryIEnumerableGenericResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets information about the API version and current user. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MetaResponseGenericResponse"];
                        "application/json": components["schemas"]["MetaResponseGenericResponse"];
                        "text/json": components["schemas"]["MetaResponseGenericResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check endpoint to verify the API is responding. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StringGenericResponse"];
                        "application/json": components["schemas"]["StringGenericResponse"];
                        "text/json": components["schemas"]["StringGenericResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets all users in the system. Requires admin authorization. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserIEnumerableGenericResponse"];
                        "application/json": components["schemas"]["UserIEnumerableGenericResponse"];
                        "text/json": components["schemas"]["UserIEnumerableGenericResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Creates a new user account. This endpoint allows anonymous access. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description The user creation request. */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateUserDto"];
                    "text/json": components["schemas"]["CreateUserDto"];
                    "application/*+json": components["schemas"]["CreateUserDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserGenericResponse"];
                        "application/json": components["schemas"]["UserGenericResponse"];
                        "text/json": components["schemas"]["UserGenericResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        /** Updates an existing user's profile information. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description The user update request. */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateUserDto"];
                    "text/json": components["schemas"]["UpdateUserDto"];
                    "application/*+json": components["schemas"]["UpdateUserDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserGenericResponse"];
                        "application/json": components["schemas"]["UserGenericResponse"];
                        "text/json": components["schemas"]["UserGenericResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/users/serviceaccounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets all service accounts. Requires admin authorization. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserIEnumerableGenericResponse"];
                        "application/json": components["schemas"]["UserIEnumerableGenericResponse"];
                        "text/json": components["schemas"]["UserIEnumerableGenericResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets a specific user by their identifier. Requires admin authorization. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The unique identifier of the user. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserGenericResponse"];
                        "application/json": components["schemas"]["UserGenericResponse"];
                        "text/json": components["schemas"]["UserGenericResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Deletes a user by their identifier. Requires super user authorization. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The identifier of the user to delete. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GenericResponse"];
                        "application/json": components["schemas"]["GenericResponse"];
                        "text/json": components["schemas"]["GenericResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets the current authenticated user's profile. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserGenericResponse"];
                        "application/json": components["schemas"]["UserGenericResponse"];
                        "text/json": components["schemas"]["UserGenericResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Records a user's acceptance of terms and conditions. This endpoint allows anonymous access. */
        get: {
            parameters: {
                query?: {
                    /** @description The user's email address. */
                    email?: string;
                    /** @description Whether the terms were accepted (default: true). */
                    accepted?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/serviceaccount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates a new service account. Requires admin authorization. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description The service account creation request. */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateUserDto"];
                    "text/json": components["schemas"]["CreateUserDto"];
                    "application/*+json": components["schemas"]["CreateUserDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserGenericResponse"];
                        "application/json": components["schemas"]["UserGenericResponse"];
                        "text/json": components["schemas"]["UserGenericResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/athletes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates multiple athlete accounts in a batch operation. Requires admin authorization. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description The batch athlete creation request. */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateAthletesDto"];
                    "text/json": components["schemas"]["CreateAthletesDto"];
                    "application/*+json": components["schemas"]["CreateAthletesDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserIEnumerableGenericResponse"];
                        "application/json": components["schemas"]["UserIEnumerableGenericResponse"];
                        "text/json": components["schemas"]["UserIEnumerableGenericResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/coaches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates multiple coach accounts in a batch operation. Requires admin authorization. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description The batch coach creation request. */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateCoachesDto"];
                    "text/json": components["schemas"]["CreateCoachesDto"];
                    "application/*+json": components["schemas"]["CreateCoachesDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserIEnumerableGenericResponse"];
                        "application/json": components["schemas"]["UserIEnumerableGenericResponse"];
                        "text/json": components["schemas"]["UserIEnumerableGenericResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Synchronizes users with an external system. Requires super user authorization. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserIEnumerableGenericResponse"];
                        "application/json": components["schemas"]["UserIEnumerableGenericResponse"];
                        "text/json": components["schemas"]["UserIEnumerableGenericResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/users/clean": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Removes inactive or invalid users from the system. Requires super user authorization. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GenericResponse"];
                        "application/json": components["schemas"]["GenericResponse"];
                        "text/json": components["schemas"]["GenericResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request model for adding a user to an entity with specified roles. */
        AddUserToEntityRequest: {
            /** @description Gets the roles to assign to the user for the entity. */
            roles: components["schemas"]["Roles"][] | null;
        };
        /** @description Request model for creating multiple athletes in a batch. */
        CreateAthletesDto: {
            /** @description Gets the list of athletes to create. */
            athletes?: components["schemas"]["CreateUserDto"][] | null;
        };
        /** @description Request model for creating multiple coaches in a batch. */
        CreateCoachesDto: {
            /** @description Gets the list of coaches to create. */
            coaches?: components["schemas"]["CreateUserDto"][] | null;
        };
        /** @description Request model for creating a new entity. */
        CreateEntityRequest: {
            /** @description Gets the name of the entity. */
            name: string | null;
            /** @description Gets the optional description of the entity. */
            description?: string | null;
            /** @description Gets the optional type of the entity. */
            entityType?: string | null;
            /**
             * Format: uuid
             * @description Gets the optional parent entity identifier.
             */
            parentEntityId?: string | null;
        };
        /** @description Data transfer object for creating a new event log entry. */
        CreateEventLogDto: {
            /** @description Gets the type of the event (maximum 100 characters). */
            eventType: string | null;
            /**
             * Format: date-time
             * @description Gets the timestamp when the event occurred.
             */
            timestamp: string;
            /**
             * Format: uuid
             * @description Gets the unique identifier of the user associated with this event.
             */
            userId: string;
            /** @description Gets optional event data as a JSON string (maximum 4000 characters). */
            eventData?: string | null;
            /** @description Gets the optional source of the event (maximum 100 characters). */
            source?: string | null;
            /**
             * Format: uuid
             * @description Gets the optional entity identifier associated with this event.
             */
            entityId?: string | null;
            /** @description Gets the optional session identifier (maximum 100 characters). */
            sessionId?: string | null;
        };
        /** @description Request model for creating multiple event log entries in a batch. */
        CreateEventLogsDto: {
            /** @description Gets the list of event logs to create. */
            eventLogs?: components["schemas"]["CreateEventLogDto"][] | null;
        };
        /** @description Data transfer object for creating a new user. */
        CreateUserDto: {
            /** @description Gets the first name of the user. */
            firstName?: string | null;
            /** @description Gets the last name of the user. */
            lastName?: string | null;
            /** @description Gets the email address of the user. */
            email?: string | null;
            /** @description Gets or sets the roles assigned to the user. */
            roles?: components["schemas"]["Roles"][] | null;
        };
        DateTimeOffsetNullableGenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
            /** Format: date-time */
            data?: string | null;
        };
        Entity: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: uuid */
            lastModifiedBy?: string | null;
            /** Format: date-time */
            lastModifiedAt?: string | null;
            isDeleted?: boolean;
            /** Format: date-time */
            deletedAt?: string | null;
            /** Format: uuid */
            deletedBy?: string | null;
            name: string | null;
            description?: string | null;
            entityType?: string | null;
            /** Format: uuid */
            parentEntityId?: string | null;
        };
        EntityGenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
            data?: components["schemas"]["Entity"];
        };
        EntityIEnumerableGenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
            data?: components["schemas"]["Entity"][] | null;
        };
        EventLog: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: uuid */
            lastModifiedBy?: string | null;
            /** Format: date-time */
            lastModifiedAt?: string | null;
            eventType: string | null;
            /** Format: date-time */
            timestamp: string;
            /** Format: uuid */
            userId: string;
            eventData?: string | null;
            source?: string | null;
            /** Format: uuid */
            entityId?: string | null;
            ipAddress?: string | null;
            userAgent?: string | null;
            sessionId?: string | null;
        };
        EventLogGenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
            data?: components["schemas"]["EventLog"];
        };
        EventLogIEnumerableGenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
            data?: components["schemas"]["EventLog"][] | null;
        };
        EventLogIEnumerablePagedResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
            data?: components["schemas"]["EventLog"][] | null;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            totalCount?: number;
        };
        EventLogMonthlySummary: {
            /** Format: int32 */
            year?: number;
            /** Format: int32 */
            month?: number;
            /** Format: int32 */
            videosCaptured?: number;
            /** Format: int32 */
            daysUsed?: number;
            /** Format: int32 */
            totalDaysInPeriod?: number;
            /** Format: double */
            usageRatio?: number;
            eventTypeCounts?: {
                [key: string]: number;
            } | null;
        };
        /** @description Data transfer object for searching event logs with filtering and paging. */
        EventLogSearchCriteriaDto: {
            /**
             * Format: uuid
             * @description Gets the optional user identifier to filter event logs.
             */
            userId?: string | null;
            /**
             * Format: uuid
             * @description Gets the optional entity identifier to filter event logs.
             */
            entityId?: string | null;
            /** @description Gets the optional event type to filter event logs. */
            eventType?: string | null;
            /**
             * Format: date-time
             * @description Gets the optional timestamp cutoff to filter out logs prior to this date.
             *     Defaults to 6 months ago from the first day of the month if not specified.
             */
            timestampFrom?: string | null;
            /**
             * Format: date-time
             * @description Gets the optional end timestamp to filter event logs up to this date.
             */
            timestampTo?: string | null;
            /**
             * Format: int32
             * @description Gets the page number for pagination. Defaults to 1.
             */
            pageNumber?: number;
            /**
             * Format: int32
             * @description Gets the page size for pagination. Defaults to 50. Maximum is 200.
             */
            pageSize?: number;
        };
        EventLogUserSummary: {
            /** Format: uuid */
            userId?: string;
            email?: string | null;
            firstName?: string | null;
            lastName?: string | null;
            monthlyData?: components["schemas"]["EventLogMonthlySummary"][] | null;
        };
        EventLogUserSummaryIEnumerableGenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
            data?: components["schemas"]["EventLogUserSummary"][] | null;
        };
        GenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
        };
        /** @description Represents user login credentials. */
        LoginInfo: {
            /** @description Gets or sets the username (email) for authentication. */
            username: string | null;
            /** @description Gets or sets the password for authentication. */
            password: string | null;
        };
        /** @description Response model containing metadata about the API and current user. */
        MetaResponse: {
            /** @description The API version. */
            version?: string | null;
            /**
             * Format: date-time
             * @description The timestamp when the API was last updated.
             */
            lastUpdated?: string;
            /** @description The current user's identifier. */
            userId?: string | null;
            /** @description The current user's email address. */
            email?: string | null;
        };
        MetaResponseGenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
            data?: components["schemas"]["MetaResponse"];
        };
        /** @enum {string} */
        Roles: "Athlete" | "Coach" | "EntityAdmin" | "OrganizationAdmin" | "Admin" | "ServiceAccount" | "AlphaTester" | "BetaTester" | "SuperUser";
        StringGenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
            data?: string | null;
        };
        StringIEnumerableGenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
            data?: string[] | null;
        };
        /** @description Request model for updating an existing entity. */
        UpdateEntityRequest: {
            /** @description Gets the updated name of the entity. */
            name: string | null;
            /** @description Gets the updated description of the entity. */
            description?: string | null;
            /** @description Gets the updated type of the entity. */
            entityType?: string | null;
            /**
             * Format: uuid
             * @description Gets the updated parent entity identifier.
             */
            parentEntityId?: string | null;
        };
        /** @description Data transfer object for updating an existing user. */
        UpdateUserDto: {
            /**
             * Format: uuid
             * @description Gets the unique identifier of the user to update.
             */
            id?: string;
            /** @description Gets the updated first name of the user. */
            firstName?: string | null;
            /** @description Gets the updated last name of the user. */
            lastName?: string | null;
            /**
             * Format: int32
             * @description Gets or sets the height of the user in inches.
             */
            heightInInches?: number | null;
            /** @description Gets or sets the color preference in hexadecimal format. */
            colorHex?: string | null;
            /**
             * Format: date
             * @description Gets or sets the birthdate of the user.
             */
            birthdate?: string | null;
            /**
             * Format: byte
             * @description Gets or sets the thumbnail image data for the user.
             */
            thumbnailImage?: string | null;
            /** @description Gets or sets the roles assigned to the user. */
            roles?: components["schemas"]["Roles"][] | null;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: uuid */
            lastModifiedBy?: string | null;
            /** Format: date-time */
            lastModifiedAt?: string | null;
            isDeleted?: boolean;
            /** Format: date-time */
            deletedAt?: string | null;
            /** Format: uuid */
            deletedBy?: string | null;
            externalId?: string | null;
            firstName?: string | null;
            lastName?: string | null;
            /** Format: int32 */
            heightInInches?: number | null;
            colorHex?: string | null;
            email: string | null;
            /** Format: date */
            birthdate?: string | null;
            /** Format: byte */
            thumbnailImage?: string | null;
            acceptedTerms?: boolean;
            confirmedAge?: boolean;
            isEmailVerified?: boolean;
            roles?: components["schemas"]["Roles"][] | null;
        };
        UserGenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
            data?: components["schemas"]["User"];
        };
        UserIEnumerableGenericResponse: {
            succeeded?: boolean;
            message?: string | null;
            errors?: string[] | null;
            data?: components["schemas"]["User"][] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
